AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  getredditstream:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 120
      Role: >-
        arn:aws:iam::288882751603:role/service-role/get_reddit_stream-role-lwi3dy7v
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Layers:
        - 'arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python-AWS-SDK:4'
        - 'arn:aws:lambda:us-east-1:288882751603:layer:reddit:1'
